<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOepwrol\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOepwrol/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOepwrol.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOepwrol\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOepwrol\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Oepwrol',
    'container.build_id' => '667014e4',
    'container.build_time' => 1532008553,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOepwrol');
